# Generated by Django 2.2.9 on 2020-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200828_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию (необязательно)', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
